@startuml
abstract class Modelo.Personagem
class Auxiliar.Consts
class Auxiliar.Desenho
class Controler.ControleDeJogo
class Controler.Fase
class Controler.Tela
class Main
class Modelo.Bala
class Modelo.CanhaoB
class Modelo.CanhaoD
class Modelo.CanhaoE
class Modelo.Cano
class Modelo.CascaDeBanana
class Modelo.Cascoh
class Modelo.Cascov
class Modelo.Chaser
class Modelo.CogumeloMal
class Modelo.Hero
class Modelo.Moeda
class Modelo.PortalCerto
class Modelo.PortalQueMata
class Modelo.PortalVoltaInicio
class Modelo.Tapete
class Modelo.cascaDeBananaEsquerda
class auxiliar.Posicao
class java.awt.Color
class java.awt.Font
class java.awt.FontMetrics
class java.awt.Graphics
class java.awt.Image
class java.awt.Toolkit
class java.awt.event.KeyEvent
class java.awt.image.BufferedImage
class java.io.File
class java.io.IOException
class java.util.ArrayList
class java.util.Timer
class java.util.TimerTask
class java.util.logging.Level
class java.util.logging.Logger
class javax.swing.ImageIcon
class javax.swing.JFrame
class javax.swing.JOptionPane
class javax.swing.SwingUtilities
interface java.awt.event.KeyListener
interface java.io.Serializable
@enduml